[package]
name = "tsgen"
description = "A random genome generator that generates template switches."
authors = ["Sebastian Schmidt <sebastian.schmidt@helsinki.fi>"]
version = "0.0.0"
edition = "2021"
license = "BSD-2-Clause"

[dependencies]
